-- Empty disposable database only; all synthetic fixtures roll back.
begin;
do $$ begin if exists(select 1 from public.profiles) then raise exception 'Use empty database'; end if; end $$;
insert into auth.users(id,email) values ('10000000-0000-4000-8000-000000000001','owner@example.test'),('10000000-0000-4000-8000-000000000002','developer@example.test');
insert into public.profiles(id,display_name,role) values ('10000000-0000-4000-8000-000000000001','Synthetic Owner','owner'),('10000000-0000-4000-8000-000000000002','Synthetic Developer','developer');
set local role authenticated;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
insert into public.teams(id,name) values('20000000-0000-4000-8000-000000000001','Synthetic Team');
do $$ declare payload jsonb; r jsonb; paid jsonb; activity uuid; version text; n int; begin
 payload='{"team_id":"20000000-0000-4000-8000-000000000001","business_date":"2020-01-01","actual_cny_handled":"1.00","fee_rate":"100.005000","calculated_fee_idr":"100.01"}';
 r=public.mutate_team_activity('create',payload,'create'); activity=(r->'activity'->>'id')::uuid;
 if r->'activity'->>'fee_status'<>'unpaid' or exists(select 1 from public.financial_outflows) then raise exception 'Premature recognition'; end if;
 if public.mutate_team_activity('create',payload,'create')<>r or (select count(*) from public.team_daily_activities)<>1 then raise exception 'Duplicate create'; end if;
 begin perform public.mutate_team_activity('create',payload||'{"fee_rate":"1"}','create'); raise exception 'Expected conflict' using errcode='ZX001'; exception when sqlstate 'P0001' then if sqlerrm<>'IDEMPOTENCY_CONFLICT' then raise; end if; end;
 begin perform public.mutate_team_activity('create',payload,'another-create'); raise exception 'Expected unique day' using errcode='ZX001'; exception when unique_violation then null; end;
 version=r->'activity'->>'updated_at';
 payload=payload||jsonb_build_object('updated_at',version,'actual_cny_handled','2.00','calculated_fee_idr','200.01');
 r=public.mutate_team_activity('edit',payload,'edit',activity);
 if r->'activity'->>'calculated_fee_idr'<>'200.01' or exists(select 1 from public.financial_outflows) then raise exception 'Unpaid edit failed'; end if;
 begin perform public.mutate_team_activity('edit',payload,'stale',activity); raise exception 'Expected stale' using errcode='ZX001'; exception when sqlstate 'P0001' then if sqlerrm<>'STALE_ACTIVITY' then raise; end if; end;
 begin perform public.mutate_team_activity('pay',jsonb_build_object('payment_date','2020-01-03','updated_at',version),'stale-pay',activity); raise exception 'Expected stale payment' using errcode='ZX001'; exception when sqlstate 'P0001' then if sqlerrm<>'STALE_ACTIVITY' then raise; end if; end;
 paid=public.mutate_team_activity('pay',jsonb_build_object('payment_date','2020-01-03','updated_at',r->'activity'->>'updated_at'),'pay',activity);
 if paid->'outflow'->>'business_date'<>'2020-01-03' or paid->'activity'->>'business_date'<>'2020-01-01' or paid->'outflow'->>'amount_idr'<>'200.01' then raise exception 'Payment date/amount failed'; end if;
 n=(select count(*) from public.audit_logs);
 if public.mutate_team_activity('pay',jsonb_build_object('payment_date','2020-01-03','updated_at',r->'activity'->>'updated_at'),'pay',activity)<>paid then raise exception 'Replay differs'; end if;
 perform public.mutate_team_activity('pay','{"payment_date":"2020-01-03"}','pay-again',activity);
 if (select count(*) from public.financial_outflows)<>1 or (select count(*) from public.audit_logs)<>n then raise exception 'Duplicate payment/audit'; end if;
 begin perform public.mutate_team_activity('pay','{"payment_date":"2020-01-04"}','wrong-day',activity); raise exception 'Expected date lock' using errcode='ZX001'; exception when sqlstate 'P0001' then if sqlerrm<>'STATE_CONFLICT' then raise; end if; end;
 begin perform public.mutate_team_activity('edit',payload,'paid-edit',activity); raise exception 'Expected paid lock' using errcode='ZX001'; exception when sqlstate 'P0001' then if sqlerrm<>'ACTIVITY_LOCKED' then raise; end if; end;
 payload='{"team_id":"20000000-0000-4000-8000-000000000001","business_date":"2020-01-01","movement_type":"received","cny_amount":"100.00"}';
 perform public.mutate_team_activity('movement',payload,'received');
 perform public.mutate_team_activity('movement',payload||'{"movement_type":"distributed","cny_amount":"30.00"}','distributed');
 perform public.mutate_team_activity('movement',payload||'{"movement_type":"adjustment","cny_amount":"-2.50"}','adjustment');
 perform public.mutate_team_activity('movement',payload||'{"business_date":"2020-01-02","cny_amount":"10.00"}','later');
 r=public.team_ledger('20000000-0000-4000-8000-000000000001','2020-01-01');
 if (r->>'balance_cny')::numeric<>67.50 or (r->>'received_cny')::numeric<>100 or jsonb_array_length(r->'movements')<>3 then raise exception 'Ledger arithmetic failed'; end if;
 r=public.team_ledger('20000000-0000-4000-8000-000000000001','2020-01-02');
 if (r->>'balance_cny')::numeric<>77.50 or (r->>'received_cny')::numeric<>10 then raise exception 'Cumulative balance failed'; end if;
 if (select count(*) from public.financial_outflows)<>1 then raise exception 'Movements generated fee'; end if;
 begin update public.team_daily_activities set fee_status='unpaid'; raise exception 'Direct write allowed' using errcode='ZX001'; exception when insufficient_privilege then null; end;
 begin delete from public.financial_outflows; raise exception 'Direct delete allowed' using errcode='ZX001'; exception when insufficient_privilege then null; end;
end $$;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000002',true);
do $$ begin
 if exists(select 1 from public.team_daily_activities) or exists(select 1 from public.financial_outflows) or exists(select 1 from public.team_movements) then raise exception 'Developer read allowed'; end if;
 begin perform public.mutate_team_activity('pay','{}','denied',gen_random_uuid()); raise exception 'Developer RPC allowed' using errcode='ZX001'; exception when insufficient_privilege then null; end;
end $$;
reset role;
rollback;
